# Giới Thiệu
Bạn đã từng thấy mã PyTorch. Bạn tự hỏi chúng thực sự làm gì?

Nếu bạn đã từng học Python để xử lý dữ liệu, bạn sẽ biết đến thư viện Numpy với khái niệm mảng (Array). Trong PyTorch, khái niệm này được gọi là Tensor (về cơ bản nó cũng là một ma trận số nhiều chiều).

Tuy nhiên, Numpy chỉ có thể chạy bằng chip xử lý thông thường (CPU), rất chậm khi gặp hàng triệu phép tính toán ma trận lớn. PyTorch giải quyết triệt để việc này bằng cách cho phép đẩy các Tensor lên chip đồ họa (GPU). Tốc độ tính toán lúc này sẽ được tăng tốc lên gấp hàng chục, hàng trăm lần.

Khi tìm hiểu về PyTorch, có lẽ bạn bị choáng ngợp bởi một loạt các lớp như nn.Module, torch.optim, grad_fn,.v.v.. Cảm giác như những hộp đen bí ẩn, kỳ diệu.

Sự thật là: Chúng không phải là thứ gì đó quá bí ẩn. Chúng chỉ là những lớp bao bọc cho đại số tuyến tính và phép tính vi phân mà bạn đã biết.

Toàn bộ quá trình huấn luyện học sâu, từ mô hình đơn giản nhất đến một LLM khổng lồ chỉ là một thuật toán 5 bước đơn giản. Mọi thứ khác chỉ là việc triển khai.

# Làm Quen Với Tensor
Đây là phần khởi tạo Tensor cơ bản trong PyTorch. Bạn sẽ học cách tạo dữ liệu dạng vector và ma trận,.v.v.

In [1]:
# Tạo Tensor 1 chiều giống vector, và tạo Tensor 2 chiều giống ma trận 3 hàng 3 cột
import torch
x = torch.tensor([1.0, 2.0, 3.0])
y = torch.zeros((3, 3))
print(f"1D Tensor: \n{x}")
print(f"2D Tensor: \n{y}")

1D Tensor: 
tensor([1., 2., 3.])
2D Tensor: 
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [2]:
# Tạo một vài Tensor có cùng kích thước nhưng giá trị bên trong khác nhau
shape = (2,3)
ones = torch.ones(shape)
zeros = torch.zeros(shape)
random = torch.randn(shape)
print(f"Ones Tensor: \n{ones}")

Ones Tensor: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [3]:
# Tạo một Tensor 2 chiều chứa các số ngẫu nhiên
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 2.0465, -1.5208, -0.1367,  1.5748],
        [-0.8910,  0.1347,  1.1725,  0.2975],
        [ 1.2833, -0.3460,  1.3477, -0.1518]])

In [4]:
# Tạo một Tensor 3 chiều chứa giá trị số 0
tensor_3d = torch.zeros(2,3,5)
tensor_3d

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [5]:
# Tạo một Tensor 1 chiều chứa chuỗi số nguyên liên tiếp từ 0 đến 9
my_torch1 = torch.arange(10)
my_torch1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# Biến đổi tensor 1 chiều [0…9] thành ma trận 2x5
my_torch2 = my_torch1.reshape(2,5)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [7]:
# Tạo tensor mới có hình dạng và kiểu giống như một tensor khác
# Đầu vào: một tensor mẫu
template = torch.tensor([[1, 2], [3, 4]])
# Tạo một tensor mới với các thuộc tính tương tự
rand_like = torch.rand_like(template, dtype=torch.float)
print(f"Template Tensor: \n{template}\n")
print(f"Rand like tensor: \n{rand_like}")

Template Tensor: 
tensor([[1, 2],
        [3, 4]])

Rand like tensor: 
tensor([[0.7837, 0.5515],
        [0.2122, 0.4748]])


In [8]:
# Các thuộc tính cơ bản của một Tensor vừa được tạo
tensor = torch.randn(2, 3)
print(tensor)
print(f"Shape: {tensor.shape}")
print(f"Datatype: {tensor.dtype}")
print(f"Device: {tensor.device}")

tensor([[-0.3685,  0.8954,  2.7409],
        [ 0.0732, -1.1353,  0.6779]])
Shape: torch.Size([2, 3])
Datatype: torch.float32
Device: cpu


**Shape:** Là một tuple mô tả kích thước. Công cụ gỡ lỗi số 1. Hầu như 90% lỗi của bạn trong PyTorch là do không khớp kích thước

**Dtype:** Kiểu dữ liệu của các số. Mặc định là float32. Điều này không phải là ngẫu nhiên

**Device:** Nơi lưu trữ tensor, CPU hoặc CUDA (GPU)


Tại sao lại dùng float32 mà không dùng số nguyên (int)?

Câu trả lời là độ dốc (Gradient). Toàn bộ cơ chế của Deep Learning hoạt động bằng cách thực hiện những điều chỉnh nhỏ liên tục đối với trọng số (weight) của mô hình, chúng ta đang nói đến tác động nhỏ, bạn không thể thay đổi tham số từ số 3 thành 3.001 nếu kiểu dữ liệu chỉ cho phép số nguyên. Vì vậy các tham số của mô hình (weights, biases) phải có kiểu dữ liệu float32 là tiêu chuẩn, chúng có thể là số nguyên nhưng những thứ cần học phải là số thực


In [9]:
# Tensor dữ liệu
x_data = torch.tensor([[1, 2], [3, 4]]) # Một ma trận 2×2 kiểu int64, đại diện cho input hoặc target. Mặc định requires_grad=False, nên autograd không theo dõi để tính gradient cho nó
# Tensor tham số (cần tính Gradient)
w = torch.tensor([[1.0], [2.0]], requires_grad=True) # Vector trọng số 2×1 kiểu float32 đặt requires_grad=True. Autograd sẽ ghi lại mọi phép toán liên quan để về sau có thể gọi backward() và nhận gradient của w (phục vụ tối ưu hoá)
print(f"Data tensor requires_grad: {x_data.requires_grad}")
print(f"Parameter tensor requires_grad: {w.requires_grad}")

Data tensor requires_grad: False
Parameter tensor requires_grad: True


Thuộc tính .grad_fn:
Mỗi tensor là kết quả của một phép toán trên tensor requires_grad sẽ có một thuộc tính đặc biệt gọi là .grad_fn. Thuộc tính này là một "dấu vết" chỉ dẫn đến hàm đã tạo ra nó.

In [10]:
# Computation Graph & .grad_fn
# Tạo đồ thị tính toán đơn giản (z=x*(a+b)), rồi gọi backward() để PyTorch tự động lan truyền đạo hàm và ghi gradient vào các tham số (a, b, x)
a = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(3.0, requires_grad=True)
x = torch.tensor(4.0, requires_grad=True)
y = a + b
z = x * y
print(f"grad_fn for z: {z.grad_fn}")
print(f"grad_fn for y: {y.grad_fn}")
print(f"grad_fn for a: {a.grad_fn}")
z.backward()
print(a.grad)

grad_fn for z: <MulBackward0 object at 0x7f7315f57550>
grad_fn for y: <AddBackward0 object at 0x7f732036bbb0>
grad_fn for a: None
tensor(4.)


In [11]:
# Cách PyTorch tự động tính đạo hàm: nó tạo biến x (cần gradient), định nghĩa hàm y=x^2+5, gọi backward() để lan truyền đạo hàm, rồi in ra x.grad, kết quả là 2x=6 tại x=3.
x = torch.tensor(3.0, requires_grad=True)
y = x**2 + 5
y.backward()
print(x.grad)

tensor(6.)


In [12]:
# Sự khác nhau giữa nhân từng phần tử (a * b) và nhân ma trận (a @ b)
a = torch.tensor([[1,2], [3,4]])
b = torch. tensor([[10,20],[30,40]])

# Nhân từng phần tử
element_wise_product = a * b
print(f"Element wise product: \n{element_wise_product}")

# Để thực hiện được phép nhân ma trận thì số cột trong ma trận thứ nhất phải bằng số hàng trong ma trận thứ 2
matrix_multip = a @ b
print(f"Matrix multip: \n{matrix_multip}")


Element wise product: 
tensor([[ 10,  40],
        [ 90, 160]])
Matrix multip: 
tensor([[ 70, 100],
        [150, 220]])


In [13]:
# Minh hoạ phép toán giảm toàn bộ tensor bằng mean()
scores = torch.tensor([[10., 5., 20.], [6., 15., 30.]])

# Phép tính này tương đương: (10 + 5 + 20 + 6 + 15 + 30) / 6
average_scores = scores.mean()
print(f"Mean: {average_scores}")

Mean: 14.333333015441895


In [14]:
# Một quy tắc đơn giản cho tensor 2D
# dim=0: Thu gọn các hàng. Thao tác theo chiều dọc
# dim=1: Thu gọn các cột. Thao tác theo chiều ngang

#          Bài tập 1   Bài tập 2   Bài tập 3
# HS1         10          5          20
# HS2         6          15          30

scores = torch.tensor([[10., 5., 20.], [6., 15., 30.]])

# Tính giá trị trung bình cho mỗi cột
avg_assignment = scores.mean(dim=0)
print(f"Average Assignment: {avg_assignment}")

# Tính giá trị trung bình cho mỗi hàng
avg_studient = scores.mean(dim=1)
print(f"Average Studient: {avg_studient}")

Average Assignment: tensor([ 8., 10., 25.])
Average Studient: tensor([11.6667, 17.0000])


In [15]:
# In cột thứ hai
x = torch.arange(12).reshape(3, 4)
# tensor ([[0, 1, 2, 3],
#          [4, 5, 6, 7],
#         [8, 9, 10, 11]])
# Lấy cột thứ ba (ở vị trí chỉ mục 2)
col_2 = x[:,2]
print(col_2)

tensor([ 2,  6, 10])


In [16]:
scores = torch.tensor([[10, 0, 5, 20, 1],
                       [1, 30, 2, 5, 0]])
# In ra chỉ số chứa số lớn nhất trong mỗi hàng
highest_index_row = torch.argmax(scores, dim=1)
print(highest_index_row)
# In ra chỉ số chứa số lớn nhất trong mỗi cột
highest_index_column = torch.argmax(scores, dim=0)
print(highest_index_column)

tensor([3, 1])
tensor([0, 1, 0, 0, 0])


In [17]:
# Chọn một phần tử từ tensor
data = torch.tensor([[10,11,12,13],
                    [20,21,22,23],
                    [30,31,32,33]])
index_to_select = torch.tensor([[2], [0], [3]])
selected_values = torch.gather(data, dim=1, index=index_to_select)
print(selected_values)

tensor([[12],
        [20],
        [33]])


In [18]:
x = torch.tensor(1.0)
w = torch.tensor(2.0, requires_grad=True) # Trọng số cần học
target = torch.tensor(0.0)

# 1. Forward Pass: Dự đoán và tính sai số
prediction = w * x
loss = (prediction - target)**2 

# 2. Backward Pass: Tính đạo hàm
loss.backward()

# 3. Kết quả đạo hàm nằm ở đâu?
print(w.grad) # Đây chính là giá trị dL/dw

tensor(4.)


# Xây Dựng Mô Hình Và Huấn Luyện Thủ Công
Dưới đây là toàn bộ quy trình tạo dữ liệu ➝ xây mô hình ➝ tính loss ➝ lan truyền gradient ➝ tối ưu cho một bài toán hồi quy tuyến tính đơn giản

In [19]:
# Giả sử tập dữ liệu của chúng ta sẽ có 10 điểm dữ liệu
N = 10
# Mỗi điểm dữ liệu có 1 đặc trưng đầu vào và 1 giá trị đầu ra
D_in = 1
D_out = 1
# Tạo dữ liệu đầu vào của chúng ta X
X = torch.randn(N, D_in)
# Tạo nhãn mục tiêu thực y bằng cách sử dụng các giá trị "thực" w và b
# Giá trị thật của W là 2.0, giá trị thật của b là 1.0
true_W = torch.tensor([[2.0]])
true_b = torch.tensor(1.0)
y_true = X @ true_W + true_b + torch.randn(N, D_out) * 0.1

# Khởi tạo các tham số của chúng ta với các giá trị ngẫu nhiên
# Hình dạng phải chính xác để thực hiện phép nhân ma trận
W = torch.randn(D_in, D_out, requires_grad=True)
b = torch.randn(1, requires_grad=True)
print(f"Initial Weight W: \n{W}\n")
print(f"Initial Bias b: \n{b}")

# Quá trình truyền tiến (Forward pass) qua mô hình của chúng ta
y_hat = X @ W + b
print(f"Predict y_hat (first 3 rows): \n{y_hat[:3]}\n")
print(f"True label y_true (first 3 rows): \n{y_true[:3]}")

# Tính loss (sử dụng MSE)
error = (y_hat - y_true)**2
loss = error.mean()
print(f"Loss: {loss}")

# Tính gradient
loss.backward() # -> để PyTorch tự tính ∂L/∂W và ∂L/∂b
# Các gradient hiện được lưu trữ trong thuộc tính .grad
print(f"Gradient for W (∂L/∂w): \n{W.grad}\n")
print(f"Gradient for b (∂L/∂b): \n{b.grad}\n")

# Khởi tạo siêu tham số (Hyperparameters)
learning_rate = 0.01
epochs = 300
# Re-initialize parameters
W,b = torch.randn(1,1, requires_grad=True), torch.randn(1, requires_grad=True)

# Training Loop
for epoch in range(epochs):
    # Truyền tiến
    y_hat = X @ W + b
    loss = torch.mean((y_hat - y_true)**2)
    
    # Truyền ngược (tính gradient)
    loss.backward()

    # Cập nhật tham số (Gradient Descent)
    with torch.no_grad():
        W -= learning_rate * W.grad
        b -= learning_rate * b.grad

    # Đặt lại gradient bằng 0 (Trong PyTorch, mỗi khi gọi loss.backward() các giá trị đạo hàm được cộng dồn vào thuộc tính .grad của từng tham số. Nếu không đặt chúng về 0, các gradient của vòng lặp hiện tại sẽ bị cộng thêm vào gradient còn sót lại từ vòng lặp trước → phép cập nhật trở nên sai lệch (giống như dùng batch lớn hơn vô tình) và mô hình khó hội tụ đúng)
    W.grad.zero_()
    b.grad.zero_()

    if epoch % 10 == 0:
        print(f"Epoch {epoch:02d}: Loss={loss.item():.4f}, W={W.item():.3f}, b={b.item():.3f}")
print(f"\nFinal Parameters: W={W.item():.3f}, b={b.item():.3f}")
print(f"True Parameters: W=2.000, b=1.000")

Initial Weight W: 
tensor([[1.4726]], requires_grad=True)

Initial Bias b: 
tensor([0.1645], requires_grad=True)
Predict y_hat (first 3 rows): 
tensor([[1.8002],
        [0.0367],
        [1.3870]], grad_fn=<SliceBackward0>)

True label y_true (first 3 rows): 
tensor([[3.2356],
        [0.7016],
        [2.6717]])
Loss: 1.523054838180542
Gradient for W (∂L/∂w): 
tensor([[-2.0786]])

Gradient for b (∂L/∂b): 
tensor([-2.2380])

Epoch 00: Loss=14.4777, W=-0.930, b=-0.068
Epoch 10: Loss=7.9638, W=-0.289, b=0.386
Epoch 20: Loss=4.4553, W=0.194, b=0.701
Epoch 30: Loss=2.5526, W=0.560, b=0.916
Epoch 40: Loss=1.5101, W=0.840, b=1.060
Epoch 50: Loss=0.9304, W=1.056, b=1.153
Epoch 60: Loss=0.6012, W=1.223, b=1.210
Epoch 70: Loss=0.4089, W=1.355, b=1.242
Epoch 80: Loss=0.2922, W=1.460, b=1.256
Epoch 90: Loss=0.2184, W=1.544, b=1.258
Epoch 100: Loss=0.1693, W=1.613, b=1.252
Epoch 110: Loss=0.1351, W=1.670, b=1.242
Epoch 120: Loss=0.1103, W=1.717, b=1.227
Epoch 130: Loss=0.0915, W=1.757, b=1.212
Ep

Hãy theo dõi tiến trình trên:
- Mỗi 10 epoch in Loss, W và b.
- Kết thúc cho thấy W≈2 và b≈1, khớp với giá trị “thật”.

# torch.nn.Linear
Lớp torch.nn.Linear thực hiện chính xác những gì mà phép toán X @ W + b thủ công của chúng ta đã làm, nn.Linear chính là làm phép tính này trên quy mô lớn. Nó nhận vào một danh sách các số, nhân chúng với các trọng số ($w$), cộng lại với nhau, rồi cộng thêm độ chệch ($b$). Nó là một vùng chứa các tensor W và b cho phép biến đổi tuyến tính và thực hiện phép toán cho chúng ta.
Hãy xem cách nó thay thế thiết lập thủ công của chúng ta.

In [20]:
# Đầu vào của mô hình có 1 đặc trưng (D_in=1)
# Đầu ra của mô hình là 1 giá trị (D_out=1)
D_in = 1
D_out = 1

# Tạo một lớp tuyến tính
linear_layer = torch.nn.Linear(in_features=D_in, out_features=D_out)

# Chúng ta có thể kiểm tra các tham số được khởi tạo ngẫu nhiên bên trong
print(f"Layer's Weight (W): {linear_layer.weight}\n")
print(f"Layer's Bias (b): {linear_layer.bias}\n")

# Bạn sử dụng nó giống như một hàm. Hãy truyền dữ liệu X của chúng ta qua nó.
# Điều này thực hiện quá trình truyền tiến: X @ W.T + b
# (Lưu ý: nn.Linear lưu trữ W dưới dạng (D_out, D_in), vì vậy nó sử dụng phép chuyển vị)
y_hat_nn = linear_layer(X)

print(f"Output of nn.Linear (first 3 rows):\n {y_hat_nn[:3]}")

Layer's Weight (W): Parameter containing:
tensor([[0.6081]], requires_grad=True)

Layer's Bias (b): Parameter containing:
tensor([-0.6639], requires_grad=True)

Output of nn.Linear (first 3 rows):
 tensor([[ 0.0115],
        [-0.7167],
        [-0.1591]], grad_fn=<SliceBackward0>)


# nn.ReLU (Rectified Linear Unit)
Đây là hàm kích hoạt phổ biến nhất cho các mạng nơron đa năng. Quy tắc của nó vô cùng đơn giản: nếu đầu vào x âm, đầu ra là 0. Nếu đầu vào x dương, đầu ra là x. Nó thường dùng để tắt các nơ ron kích hoạt âm.
Tham số có thể học: KHÔNG. Đây là một hàm toán học cố định.

ReLU(x) = max(0, x)

In [21]:
# Tạo một lớp hàm kích hoạt ReLU
relu = torch.nn.ReLU()

# Tạo dữ liệu mẫu với giá trị âm và dương
sample_data = torch.tensor([-2.0, -0.5, 0.0, 0.5, 2.0])

# Áp dụng kích hoạt
activated_data = relu(sample_data)

print(f"Original Data:      {sample_data}")
print(f"Data after ReLU:    {activated_data}")

Original Data:      tensor([-2.0000, -0.5000,  0.0000,  0.5000,  2.0000])
Data after ReLU:    tensor([0.0000, 0.0000, 0.0000, 0.5000, 2.0000])


# nn.GELU (Gaussian Error Linear Unit)
Đây là tiêu chuẩn hiện đại cho các mô hình hiệu năng cao, đặc biệt là các mô hình Transformer như BERT,GPT và ViT. Đây là một phiên bản "xác suất" mượt mà hơn của ReLU. Thay vì một công tắc "tắt" cứng ở mức 0, nó giảm trọng số đầu vào một cách mượt mà dựa trên độ lớn của chúng.
Vì đồ thị của nó là một đường cong không có điểm gãy, đạo hàm của nó tồn tại ở mọi nơi. Điều này giúp các thuật toán tối ưu (như Gradient Descent) cập nhật trọng số mượt mà hơn, mô hình dễ hội tụ hơn. Các giá trị âm nhỏ vẫn giữ lại được một chút thông tin, giúp mạng neural giữ được "sức sống" và học được các đặc trưng phức tạp tốt hơn.

GELU(x)=x∗Φ(x)

In [22]:
# Tạo lớp chức năng kích hoạt GELU
gelu = torch.nn.GELU()

# Sử dụng cùng một dữ liệu mẫu ở trên
sample_data = torch.tensor([-2.0, -0.5, 0.0, 0.5, 2.0])

# Áp dụng kích hoạt
activated_data = gelu(sample_data)

print(f"Original Data:      {sample_data}")
print(f"Data after GELU:    {activated_data}")

Original Data:      tensor([-2.0000, -0.5000,  0.0000,  0.5000,  2.0000])
Data after GELU:    tensor([-0.0455, -0.1543,  0.0000,  0.3457,  1.9545])


# nn.Softmax
Softmax là một hàm kích hoạt đặc biệt được sử dụng trên lớp đầu ra cuối cùng của một mô hình phân loại. Nhiệm vụ của nó là lấy một vectơ các điểm số thô, không giới hạn (gọi là logit) và chuyển đổi chúng thành một phân phối xác suất.

In [23]:
# Hàm Softmax phải được chỉ định chiều nào chứa các điểm số cần được chuẩn hóa.
# Đối với một loạt dự đoán, đây thường là chiều cuối cùng (dim=-1 hoặc dim=1).
softmax = torch.nn.Softmax(dim=-1)

# Hãy tạo một số logit mẫu cho một batch gồm 2 mục, với 4 lớp khả thi
# Số càng cao nghĩa là mô hình càng tự tin hơn về lớp đó.
logits = torch.tensor([
    [1.0, 3.0, 0.5, 1.5],  # Logits for item 1
    [-1.0, 2.0, 1.0, 0.0]   # Logits for item 2
])

# Áp dụng softmax
probabilities = softmax(logits)

print(f"Original Logits:\n {logits}\n")
print(f"Output Probabilities:\n {probabilities}\n")
print(f"Sum of probabilities for item 1: {probabilities[0].sum()}")
print(f"Sum of probabilities for item 2: {probabilities[1].sum()}")

Original Logits:
 tensor([[ 1.0000,  3.0000,  0.5000,  1.5000],
        [-1.0000,  2.0000,  1.0000,  0.0000]])

Output Probabilities:
 tensor([[0.0939, 0.6942, 0.0570, 0.1549],
        [0.0321, 0.6439, 0.2369, 0.0871]])

Sum of probabilities for item 1: 1.0
Sum of probabilities for item 2: 1.0000001192092896


# nn.Embedding
Máy tính không hiểu từ ngữ; chúng hiểu số. Lớp Embedding là cầu nối giữa ngôn ngữ con người và thế giới vectơ bên trong của mô hình. Nó hoạt động như một bảng tra cứu có thể học được, trong đó mỗi từ (hoặc token) trong từ vựng được ánh xạ tới một vectơ dày đặc gồm các số thực. Ý tưởng cốt lõi là thông qua quá trình huấn luyện, mô hình sẽ học cách đặt các từ có nghĩa tương tự gần nhau hơn trong không gian vectơ này.
Đoạn mã dưới đây minh hoạ cách Embedding layer biến ID của từ thành vector số thực để mô hình có thể học được ý nghĩa của từ.

In [24]:
# Hãy định nghĩa một vốn từ vựng nhỏ và kích thước nhúng.
vocab_size = 10       # Chúng ta có 10 từ trong từ vựng của mình
embedding_dim = 3     # Mỗi từ sẽ được biểu diễn bằng một vectơ 3 chiều

# Tạo lớp nhúng (embedding)
embedding_layer = torch.nn.Embedding(num_embeddings=vocab_size, embedding_dim=embedding_dim)

# Đầu vào: Một loạt các câu đã được mã hóa. Hãy tạo một loạt gồm 1 câu với 4 từ.
# Các số là ID số nguyên cho mỗi từ trong từ vựng của chúng ta.
input_ids = torch.tensor([[1, 5, 0, 8]]) # Shape: (batch_size=1, sequence_length=4)

# Lấy các vectơ cho câu của chúng ta
word_vectors = embedding_layer(input_ids)

print(f"Embedding Layer's Weight Matrix (shape {embedding_layer.weight.shape}):\n {embedding_layer.weight.data}\n")
print(f"Input Token IDs (shape {input_ids.shape}):\n {input_ids}\n")
print(f"Output Word Vectors (shape {word_vectors.shape}):\n {word_vectors}")

Embedding Layer's Weight Matrix (shape torch.Size([10, 3])):
 tensor([[ 0.3939, -0.6124, -0.2182],
        [ 1.6067, -1.1429, -1.2425],
        [ 2.1195, -1.0583,  0.6879],
        [ 0.7129, -1.2261, -0.4173],
        [ 0.4993,  0.1500, -0.3586],
        [-0.2317, -0.3927,  0.7056],
        [-1.1966,  0.3661,  0.4609],
        [-0.0028,  0.2498,  0.8344],
        [-0.6820,  0.9394,  1.0213],
        [ 0.0677, -0.2730,  2.0714]])

Input Token IDs (shape torch.Size([1, 4])):
 tensor([[1, 5, 0, 8]])

Output Word Vectors (shape torch.Size([1, 4, 3])):
 tensor([[[ 1.6067, -1.1429, -1.2425],
         [-0.2317, -0.3927,  0.7056],
         [ 0.3939, -0.6124, -0.2182],
         [-0.6820,  0.9394,  1.0213]]], grad_fn=<EmbeddingBackward0>)


# nn.LayerNorm (Layer Normalization)
Khi dữ liệu chảy qua nhiều lớp của mạng nơ-ron sâu, quy mô của các con số (kích hoạt) có thể bùng nổ hoặc biến mất, khiến quá trình huấn luyện không ổn định. Chuẩn hóa lớp (Layer Normalization - LN) là một kỹ thuật mạnh mẽ giúp ổn định quá trình huấn luyện, giữ cho các giá trị luôn nằm trong một phạm vi ổn định (trung bình bằng 0, độ lệch chuẩn bằng 1), giúp mô hình học nhanh hơn và mượt mà hơn.

In [25]:
# LayerNorm cần biết hình dạng của các đặc trưng mà nó đang chuẩn hóa.
# Các vectơ từ của chúng ta từ ví dụ nhúng có chiều đặc trưng là 3.
feature_dim = 3
norm_layer = torch.nn.LayerNorm(normalized_shape=feature_dim)

# Đầu vào: Một loạt các vectơ đặc trưng. Hãy tạo một vectơ.
input_features = torch.tensor([[[1.0, 2.0, 3.0], [10.0, 20.0, 30.0]]]) # Shape (1, 2, 3)

# Áp dụng chuẩn hóa (normalization)
normalized_features = norm_layer(input_features)

# Hãy kiểm tra giá trị trung bình và độ lệch chuẩn của kết quả đầu ra.
output_mean = normalized_features.mean(dim=-1)
output_std = normalized_features.std(dim=-1)

print(f"Input Features:\n {input_features}\n")
print(f"Normalized Features:\n {normalized_features}\n")
print(f"Mean of each output vector (should be ~0): {output_mean}")
print(f"Std Dev of each output vector (should be ~1): {output_std}")

Input Features:
 tensor([[[ 1.,  2.,  3.],
         [10., 20., 30.]]])

Normalized Features:
 tensor([[[-1.2247,  0.0000,  1.2247],
         [-1.2247,  0.0000,  1.2247]]], grad_fn=<NativeLayerNormBackward0>)

Mean of each output vector (should be ~0): tensor([[0., 0.]], grad_fn=<MeanBackward1>)
Std Dev of each output vector (should be ~1): tensor([[1.2247, 1.2247]], grad_fn=<StdBackward0>)


# nn.Dropout
Dropout là một kỹ thuật điều chỉnh đơn giản nhưng cực kỳ hiệu quả để ngăn ngừa hiện tượng quá khớp (overfitting). Trong quá trình huấn luyện, sự phụ thuộc lẫn nhau quá mức giữa các neuron dẫn đến một căn bệnh kinh điển: Overfitting (Quá khớp / Học vẹt). Mạng neural học thuộc lòng dữ liệu huấn luyện rất tốt, nhưng khi gặp dữ liệu thực tế mới lạ thì đoán sai bét. 

Giải pháp Dropout: Trong mỗi lượt huấn luyện, nó sẽ ngẫu nhiên chọn ra một tỷ lệ phần trăm neuron nhất định và tạm thời "tắt" chúng đi (biến giá trị của chúng thành 0). Điều này buộc mạng phải học các biểu diễn dư thừa và ngăn nó trở nên quá phụ thuộc vào bất kỳ một nơ-ron nào. Nó giống như việc buộc một đội phải luyện tập với các thành viên vắng mặt ngẫu nhiên, làm cho toàn đội trở nên mạnh mẽ và phối hợp tốt hơn.

Vì các neuron bị tắt liên tục và ngẫu nhiên qua từng lượt, không neuron nào có thể ỷ lại vào neuron khác. Mỗi neuron đều phải tự nỗ lực học cách trích xuất những đặc trưng (features) hữu ích nhất. Kết quả là ta có một mạng neural "mạnh mẽ" hơn rất nhiều.


In [26]:
# Tạo một lớp dropout để loại bỏ 50% đầu vào.
dropout_layer = torch.nn.Dropout(p=0.5) # Tham số p=0.5 có nghĩa là 50% cơ hội các neuron sẽ bị biến thành 0 ở mỗi lượt học (Forward pass).

# Đầu vào: Một tensor đơn giản gồm toàn số 1 để ta có thể thấy rõ hiệu ứng.
input_tensor = torch.ones(1, 10) # Shape (1, 10)

# QUAN TRỌNG: Dropout chỉ hoạt động trong quá trình huấn luyện (train). 
# Bạn phải cho lớp biết nó đang ở chế độ huấn luyện bằng .train() hoặc chế độ đánh giá bằng .eval().
# Khi Train (.train()): Dropout hoạt động hết công suất, tắt mở ngẫu nhiên các neuron để ép mạng neural phải tự lập và chống học vẹt.
# Khi Test/Dự đoán (.eval()): Chúng ta cần mô hình đưa ra câu trả lời chính xác và ổn định nhất, nên Dropout sẽ tự động được tắt đi completely (p = 0). Tất cả các neuron đều được giữ lại để cùng nhau đồng lòng đưa ra kết quả.
dropout_layer.train() # Kích hoạt dropout
output_during_train = dropout_layer(input_tensor)

dropout_layer.eval() # Tắt dropout
output_during_eval = dropout_layer(input_tensor)

print(f"Input Tensor:\n {input_tensor}\n")
print(f"Output during training (randomly zeroed and scaled):\n {output_during_train}\n")
print(f"Output during evaluation (identity function):\n {output_during_eval}")

Input Tensor:
 tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Output during training (randomly zeroed and scaled):
 tensor([[2., 0., 2., 0., 0., 0., 2., 2., 2., 2.]])

Output during evaluation (identity function):
 tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


# Xây dựng Mô hình & Vòng lặp Huấn luyện Chuyên nghiệp
Trong các đoạn mã trước "mô hình" của chúng ta chỉ là một tập hợp lỏng lẻo các tensor (W, b) và vòng lặp huấn luyện là một quy trình thủ công từng bước một. Điều này không bền vững khi mở rộng. PyTorch cung cấp hai trừu tượng cốt lõi để giải quyết vấn đề này: nn.Module để tổ chức kiến trúc mô hình của chúng ta và torch.optim để tự động hóa quá trình tối ưu hóa.

Nếu nn.Linear và các lớp khác là những viên gạch LEGO, thì nn.Module là cuốn sách hướng dẫn và tấm đế. Nó cung cấp một cấu trúc chuẩn để xác định cách các viên gạch của bạn kết nối

Mục tiêu của chúng ta là tái cấu trúc toàn bộ mã "từ đầu" của chúng ta theo phong cách PyTorch sạch sẽ và có khả năng mở rộng.

In [27]:
import torch
import torch.nn as nn
import torch.optim as optim

# Bản Thết Kế Model. Kế thừa từ nn.Module
class LinearRegressionModel(nn.Module):
    def __init__(self, in_features, out_features):
        # Gọi hàm tạo của lớp cha (nn.Module)
        super().__init__()
        self.linear_layer = nn.Linear(in_features, out_features)

    def forward(self, x):
        return self.linear_layer(x)

# Khởi tạo mô hình (1 đầu vào, 1 đầu ra)
model = LinearRegressionModel(in_features=1, out_features=1)

# Tạo Dữ Liệu Để Model Học
Giả sử ta có bài toán: Số giờ học (X) và Điểm thi thực tế (y)
Quy luật thực tế ngầm định ở đây là: y = 2 * X + 1

In [28]:
X_train = torch.tensor([[1.0], [2.0], [3.0], [4.0], [5.0]], dtype=torch.float32)
y_true  = torch.tensor([[2.0], [4.0], [6.0], [8.0], [10.0]], dtype=torch.float32)

# Tố Ưu Hóa: torch.optim
Tiếp theo, chúng ta thay thế bước cập nhật trọng số thủ công: W -= learning_rate * W.grad. Một trình tối ưu hóa từ thư viện torch.optim sẽ gói gọn logic này. Chúng ta cung cấp cho nó các tham số của mô hình cần quản lý và tốc độ học.

Các trình tối ưu hóa phổ biến nhất là:

optim.SGD: Stochastic Gradient Descent. Đây chính xác là những gì chúng ta đã triển khai thủ công.

optim.Adam: Một trình tối ưu hóa thích ứng tiên tiến hơn, thường là lựa chọn mặc định để huấn luyện mạng nơ-ron sâu. Nó điều chỉnh tốc độ học cho từng tham số riêng lẻ.

In [29]:
import torch.optim as optim

# Siêu tham số (Hyperparameters)
learning_rate = 0.01

# Tạo một trình tối ưu hóa Adam
# Chúng ta truyền model.parameters() để cho trình tối ưu hóa biết nó nên quản lý những tensor nào.
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

# Sử dụng hàm mất mát được xây dựng sẵn từ torch.nn
loss_fn = nn.MSELoss() # Sai số bình phương trung bình (Mean Squared Error Loss)

# Vòng lặp huấn luyện cuối cùng, gọn gàng
Bây giờ chúng ta có thể viết lại vòng lặp huấn luyện. 5 bước thủ công được thay thế bằng 3 lệnh cấp cao, thanh lịch. Đây là mẫu vòng lặp huấn luyện phổ biến mà bạn sẽ thấy trong 99% mã PyTorch.

optimizer.zero_grad(): Thay thế lệnh .grad.zero_() thủ công của chúng ta cho tất cả các tham số.

loss.backward(): Tương tự như trước, tính toán độ dốc cho tất cả các tham số.

optimizer.step(): Thay thế việc cập nhật trọng số thủ công của chúng ta cho tất cả các tham số bằng cách sử dụng logic của trình tối ưu hóa đã chọn (ví dụ: Adam).

In [30]:
print("--- TRƯỚC KHI HỌC ---")
for name, param in model.named_parameters():
    print(f"{name}: {param.data.item():.4f}") # In ra weight và bias ngẫu nhiên ban đầu
print("-" * 40)

model.train() # Chuyển sang chế độ huấn luyện

--- TRƯỚC KHI HỌC ---
linear_layer.weight: 0.2306
linear_layer.bias: -0.3281
----------------------------------------


LinearRegressionModel(
  (linear_layer): Linear(in_features=1, out_features=1, bias=True)
)

In [31]:
# Khở tạo epochs để model học 100 lượt
epochs = 100

for epoch in range(epochs):
    # Dự đoán (Forward Pass) ###
    y_pred = model(X_train)
    
    # Tính Loss, sử dụng hàm mất mát được xây dựng sẵn trước đó.
    loss = loss_fn(y_pred, y_true)

    # 1. Xóa các gradient cũ từ lượt trước để không bị cộng dồn
    optimizer.zero_grad()
    
    # 2. Tính đạo hàm. Lan truyền ngược (Backpropagation) để tính xem cần sửa weight/bias bao nhiêu
    loss.backward()
    
    # 3. Cập nhật các tham số mới dựa trên thuật toán Adam
    optimizer.step()

    # Tùy chọn: In tiến độ
    if (epoch + 1) % 10 == 0:
        print(f"Epoch {epoch+1}/100 | Loss = {loss.item():.4f}")

print("-" * 40)
print("--- SAU KHI HỌC 100 LƯỢT ---")
# Lúc này mô hình sẽ tự dò ra weight xấp xỉ 2.0 và bias xấp xỉ 1.0
for name, param in model.named_parameters():
    print(f"{name}: {param.data.item():.4f}")

Epoch 10/100 | Loss = 33.4869
Epoch 20/100 | Loss = 28.8351
Epoch 30/100 | Loss = 24.6299
Epoch 40/100 | Loss = 20.8804
Epoch 50/100 | Loss = 17.5752
Epoch 60/100 | Loss = 14.6896
Epoch 70/100 | Loss = 12.1925
Epoch 80/100 | Loss = 10.0497
Epoch 90/100 | Loss = 8.2261
Epoch 100/100 | Loss = 6.6876
----------------------------------------
--- SAU KHI HỌC 100 LƯỢT ---
linear_layer.weight: 1.0888
linear_layer.bias: 0.5230


Lúc đầu: Trọng số weight và bias được PyTorch khởi tạo hoàn toàn ngẫu nhiên (ví dụ: weight = 1.5003, bias = 0.2229). Mô hình đoán mò nên Loss sẽ rất cao.

Quá trình học: Qua mỗi epoch, lệnh loss.backward() sẽ tính toán hướng đi đúng, và optimizer.step() sẽ nhích weight và bias một chút về phía câu trả lời đúng.

Kết quả: Sau 100 lượt, bạn sẽ thấy weight tiến rất sát về số 2.0 và bias tiến rất sát về số 1.0. Mô hình đã tự giải mã được quy luật toán học của dữ liệu một cách hoàn chỉnh!

Đến bước này, bạn đã thực sự làm chủ được một chu trình huấn luyện Machine Learning/Deep Learning cơ bản bằng PyTorch rồi đấy.